{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "The Sims 4",
                    "category":  0,
                    "gameTitle":  "The Sims 4",
                    "description":  "Mode switching, game speed, build tools and the cheat console. The Sims 4 defaults.",
                    "tags":  "[\"life sim\",\"building\",\"sandbox\",\"ea\"]",
                    "icon":  "🏡",
                    "color":  "#22c55e",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Live Mode\"},{\"id\":2,\"name\":\"Buy Mode\"},{\"id\":3,\"name\":\"Build Mode\"},null,null,null,{\"id\":4,\"name\":\"Pause\"},{\"id\":5,\"name\":\"Normal Speed\"},{\"id\":6,\"name\":\"Fast Speed\"},{\"id\":7,\"name\":\"Ultra Speed\"},null,null,{\"id\":8,\"name\":\"Rotate Left\"},{\"id\":9,\"name\":\"Rotate Right\"},{\"id\":10,\"name\":\"Undo\"},{\"id\":11,\"name\":\"Redo\"},{\"id\":12,\"name\":\"Delete\"},null,{\"id\":13,\"name\":\"Cheat Console\"},{\"id\":14,\"name\":\"Save\"},{\"id\":15,\"name\":\"Screenshot\"},{\"id\":16,\"name\":\"Record Video\"},null,null]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Live Mode",
                     "executable":  "keyboard:F1",
                     "icon":  "👥",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Modes",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F1",
                     "keyboardShortcut":  "F1",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Buy Mode",
                     "executable":  "keyboard:F2",
                     "icon":  "🛒",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Modes",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F2",
                     "keyboardShortcut":  "F2",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Build Mode",
                     "executable":  "keyboard:F3",
                     "icon":  "🔨",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Modes",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F3",
                     "keyboardShortcut":  "F3",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Pause",
                     "executable":  "keyboard:P",
                     "icon":  "⏸️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Speed",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "P",
                     "keyboardShortcut":  "P",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Normal Speed",
                     "executable":  "keyboard:1",
                     "icon":  "▶️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Speed",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1",
                     "keyboardShortcut":  "1",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Fast Speed",
                     "executable":  "keyboard:2",
                     "icon":  "⏩",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Speed",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2",
                     "keyboardShortcut":  "2",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Ultra Speed",
                     "executable":  "keyboard:3",
                     "icon":  "⏭️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Speed",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3",
                     "keyboardShortcut":  "3",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Rotate Left",
                     "executable":  "keyboard:COMMA",
                     "icon":  "↩️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Build",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "COMMA",
                     "keyboardShortcut":  "COMMA",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Rotate Right",
                     "executable":  "keyboard:PERIOD",
                     "icon":  "↪️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Build",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "PERIOD",
                     "keyboardShortcut":  "PERIOD",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Undo",
                     "executable":  "keyboard:CTRL+Z",
                     "icon":  "⬅️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Build",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+Z",
                     "keyboardShortcut":  "CTRL+Z",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Redo",
                     "executable":  "keyboard:CTRL+Y",
                     "icon":  "➡️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Build",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+Y",
                     "keyboardShortcut":  "CTRL+Y",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Delete",
                     "executable":  "keyboard:DELETE",
                     "icon":  "🗑️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Build",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "DELETE",
                     "keyboardShortcut":  "DELETE",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Cheat Console",
                     "executable":  "keyboard:CTRL+SHIFT+C",
                     "icon":  "🖥️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Utility",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+C",
                     "keyboardShortcut":  "CTRL+SHIFT+C",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "Save",
                     "executable":  "keyboard:CTRL+S",
                     "icon":  "💾",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Utility",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+S",
                     "keyboardShortcut":  "CTRL+S",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  15,
                     "name":  "Screenshot",
                     "executable":  "keyboard:C",
                     "icon":  "📸",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Utility",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "C",
                     "keyboardShortcut":  "C",
                     "position":  14,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  16,
                     "name":  "Record Video",
                     "executable":  "keyboard:V",
                     "icon":  "🎥",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#22c55e",
                     "description":  "The Sims 4: Utility",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "V",
                     "keyboardShortcut":  "V",
                     "position":  15,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}