{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Baldur\u0027s Gate 3",
                    "category":  0,
                    "gameTitle":  "Baldur\u0027s Gate 3",
                    "description":  "Party selection, turn-based toggle, every panel and quicksave on one deck. Baldur\u0027s Gate 3 defaults.",
                    "tags":  "[\"rpg\",\"crpg\",\"turn-based\",\"larian\"]",
                    "icon":  "🐉",
                    "color":  "#7c3aed",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Turn-Based\"},{\"id\":2,\"name\":\"Jump\"},{\"id\":3,\"name\":\"Hide\"},{\"id\":4,\"name\":\"Highlight\"},null,null,{\"id\":5,\"name\":\"Char 1\"},{\"id\":6,\"name\":\"Char 2\"},{\"id\":7,\"name\":\"Char 3\"},{\"id\":8,\"name\":\"Char 4\"},null,null,{\"id\":9,\"name\":\"Inventory\"},{\"id\":10,\"name\":\"Character\"},{\"id\":11,\"name\":\"Spellbook\"},{\"id\":12,\"name\":\"Journal\"},{\"id\":13,\"name\":\"Map\"},null,{\"id\":14,\"name\":\"Hotbar 1\"},{\"id\":15,\"name\":\"Hotbar 2\"},{\"id\":16,\"name\":\"Hotbar 3\"},{\"id\":17,\"name\":\"Hotbar 4\"},{\"id\":18,\"name\":\"Hotbar 5\"},null,{\"id\":19,\"name\":\"Quicksave\"},{\"id\":20,\"name\":\"Quickload\"},{\"id\":21,\"name\":\"Menu\"},null,null,null]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Turn-Based",
                     "executable":  "keyboard:SHIFT+SPACE",
                     "icon":  "⏳",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SHIFT+SPACE",
                     "keyboardShortcut":  "SHIFT+SPACE",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Jump",
                     "executable":  "keyboard:Z",
                     "icon":  "🤸",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Z",
                     "keyboardShortcut":  "Z",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Hide",
                     "executable":  "keyboard:C",
                     "icon":  "🫥",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "C",
                     "keyboardShortcut":  "C",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Highlight",
                     "executable":  "keyboard:ALT",
                     "icon":  "✨",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "ALT",
                     "keyboardShortcut":  "ALT",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Char 1",
                     "executable":  "keyboard:F1",
                     "icon":  "1️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F1",
                     "keyboardShortcut":  "F1",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Char 2",
                     "executable":  "keyboard:F2",
                     "icon":  "2️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F2",
                     "keyboardShortcut":  "F2",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Char 3",
                     "executable":  "keyboard:F3",
                     "icon":  "3️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F3",
                     "keyboardShortcut":  "F3",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Char 4",
                     "executable":  "keyboard:F4",
                     "icon":  "4️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F4",
                     "keyboardShortcut":  "F4",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Inventory",
                     "executable":  "keyboard:I",
                     "icon":  "🎒",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Panels",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "I",
                     "keyboardShortcut":  "I",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Character",
                     "executable":  "keyboard:N",
                     "icon":  "🧝",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Panels",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "N",
                     "keyboardShortcut":  "N",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Spellbook",
                     "executable":  "keyboard:K",
                     "icon":  "📖",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Panels",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "K",
                     "keyboardShortcut":  "K",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Journal",
                     "executable":  "keyboard:J",
                     "icon":  "📜",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Panels",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "J",
                     "keyboardShortcut":  "J",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Map",
                     "executable":  "keyboard:M",
                     "icon":  "🗺️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Panels",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "M",
                     "keyboardShortcut":  "M",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "Hotbar 1",
                     "executable":  "keyboard:1",
                     "icon":  "1️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Hotbar",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1",
                     "keyboardShortcut":  "1",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  15,
                     "name":  "Hotbar 2",
                     "executable":  "keyboard:2",
                     "icon":  "2️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Hotbar",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2",
                     "keyboardShortcut":  "2",
                     "position":  14,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  16,
                     "name":  "Hotbar 3",
                     "executable":  "keyboard:3",
                     "icon":  "3️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Hotbar",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3",
                     "keyboardShortcut":  "3",
                     "position":  15,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  17,
                     "name":  "Hotbar 4",
                     "executable":  "keyboard:4",
                     "icon":  "4️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Hotbar",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4",
                     "keyboardShortcut":  "4",
                     "position":  16,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  18,
                     "name":  "Hotbar 5",
                     "executable":  "keyboard:5",
                     "icon":  "5️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Hotbar",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "5",
                     "keyboardShortcut":  "5",
                     "position":  17,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  19,
                     "name":  "Quicksave",
                     "executable":  "keyboard:F5",
                     "icon":  "💾",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Session",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F5",
                     "keyboardShortcut":  "F5",
                     "position":  18,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  20,
                     "name":  "Quickload",
                     "executable":  "keyboard:F8",
                     "icon":  "📂",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Session",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F8",
                     "keyboardShortcut":  "F8",
                     "position":  19,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  21,
                     "name":  "Menu",
                     "executable":  "keyboard:ESC",
                     "icon":  "⏸️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#7c3aed",
                     "description":  "Baldur\u0027s Gate 3: Session",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "ESC",
                     "keyboardShortcut":  "ESC",
                     "position":  20,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}