{
  "formatVersion": "2.1",
  "sanitized": true,
  "exportDate": "2026-07-27T01:19:03.4754307Z",
  "profile": {
    "name": "MSFS Airliner",
    "category": 0,
    "gameTitle": "Microsoft Flight Simulator",
    "description": "Gear, flaps, lights, autopilot and views for airliner and GA flying. Defaults for MSFS 2020/2024.",
    "tags": "[\u0022flight\u0022,\u0022sim\u0022,\u0022aviation\u0022,\u0022autopilot\u0022]",
    "icon": "\u2708\uFE0F",
    "color": "#3b82f6",
    "backgroundImage": null,
    "executableName": null,
    "isFavorite": false,
    "layoutSettings": "{\u0022gridSize\u0022:6,\u0022appsPerPage\u0022:36,\u0022spacing\u0022:\u0022medium\u0022,\u0022showLabels\u0022:true}",
    "appSettings": "{}"
  },
  "pages": [
    {
      "pageIndex": 0,
      "pageName": "Main",
      "pageData": "[{\u0022id\u0022:170,\u0022name\u0022:\u0022Gear\u0022},{\u0022id\u0022:171,\u0022name\u0022:\u0022Flaps Up\u0022},{\u0022id\u0022:172,\u0022name\u0022:\u0022Flaps Down\u0022},{\u0022id\u0022:173,\u0022name\u0022:\u0022Spoilers\u0022},{\u0022id\u0022:174,\u0022name\u0022:\u0022Parking Brake\u0022},null,{\u0022id\u0022:175,\u0022name\u0022:\u0022Autopilot\u0022},{\u0022id\u0022:176,\u0022name\u0022:\u0022Heading Hold\u0022},{\u0022id\u0022:177,\u0022name\u0022:\u0022Altitude Hold\u0022},{\u0022id\u0022:178,\u0022name\u0022:\u0022Approach\u0022},{\u0022id\u0022:179,\u0022name\u0022:\u0022Nav Hold\u0022},null,{\u0022id\u0022:180,\u0022name\u0022:\u0022Landing Lights\u0022},{\u0022id\u0022:181,\u0022name\u0022:\u0022Strobe\u0022},{\u0022id\u0022:182,\u0022name\u0022:\u0022Panel Lights\u0022},null,null,null,{\u0022id\u0022:183,\u0022name\u0022:\u0022Cockpit View\u0022},{\u0022id\u0022:184,\u0022name\u0022:\u0022External View\u0022},null,null,null,null,{\u0022id\u0022:185,\u0022name\u0022:\u0022Pause\u0022},null,null,null,null,null]",
      "layoutConfig": "{}"
    }
  ],
  "apps": [
    {
      "id": 170,
      "name": "Gear",
      "executable": "keyboard:G",
      "icon": "\uD83D\uDEDE",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Airframe",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "G",
      "keyboardShortcut": "G",
      "position": 0,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 171,
      "name": "Flaps Up",
      "executable": "keyboard:F6",
      "icon": "\uD83D\uDD3C",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Airframe",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "F6",
      "keyboardShortcut": "F6",
      "position": 1,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 172,
      "name": "Flaps Down",
      "executable": "keyboard:F7",
      "icon": "\uD83D\uDD3D",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Airframe",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "F7",
      "keyboardShortcut": "F7",
      "position": 2,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 173,
      "name": "Spoilers",
      "executable": "keyboard:SLASH",
      "icon": "\uD83E\uDE82",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Airframe",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "SLASH",
      "keyboardShortcut": "SLASH",
      "position": 3,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 174,
      "name": "Parking Brake",
      "executable": "keyboard:CTRL\u002BPERIOD",
      "icon": "\uD83C\uDD7F\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Airframe",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "CTRL\u002BPERIOD",
      "keyboardShortcut": "CTRL\u002BPERIOD",
      "position": 4,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 175,
      "name": "Autopilot",
      "executable": "keyboard:Z",
      "icon": "\uD83E\uDD16",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Autopilot",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "Z",
      "keyboardShortcut": "Z",
      "position": 5,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 176,
      "name": "Heading Hold",
      "executable": "keyboard:CTRL\u002BH",
      "icon": "\uD83E\uDDED",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Autopilot",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "CTRL\u002BH",
      "keyboardShortcut": "CTRL\u002BH",
      "position": 6,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 177,
      "name": "Altitude Hold",
      "executable": "keyboard:CTRL\u002BZ",
      "icon": "\uD83D\uDCCF",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Autopilot",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "CTRL\u002BZ",
      "keyboardShortcut": "CTRL\u002BZ",
      "position": 7,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 178,
      "name": "Approach",
      "executable": "keyboard:CTRL\u002BA",
      "icon": "\uD83D\uDEEC",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Autopilot",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "CTRL\u002BA",
      "keyboardShortcut": "CTRL\u002BA",
      "position": 8,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 179,
      "name": "Nav Hold",
      "executable": "keyboard:CTRL\u002BN",
      "icon": "\uD83D\uDDFA\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Autopilot",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "CTRL\u002BN",
      "keyboardShortcut": "CTRL\u002BN",
      "position": 9,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 180,
      "name": "Landing Lights",
      "executable": "keyboard:CTRL\u002BL",
      "icon": "\uD83D\uDCA1",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Lights",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "CTRL\u002BL",
      "keyboardShortcut": "CTRL\u002BL",
      "position": 10,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 181,
      "name": "Strobe",
      "executable": "keyboard:O",
      "icon": "\u2728",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Lights",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "O",
      "keyboardShortcut": "O",
      "position": 11,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 182,
      "name": "Panel Lights",
      "executable": "keyboard:SHIFT\u002BL",
      "icon": "\uD83D\uDD26",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Lights",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "SHIFT\u002BL",
      "keyboardShortcut": "SHIFT\u002BL",
      "position": 12,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 183,
      "name": "Cockpit View",
      "executable": "keyboard:F1",
      "icon": "\uD83C\uDF9B\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Views",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "F1",
      "keyboardShortcut": "F1",
      "position": 13,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 184,
      "name": "External View",
      "executable": "keyboard:F3",
      "icon": "\uD83D\uDEE9\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Views",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "F3",
      "keyboardShortcut": "F3",
      "position": 14,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 185,
      "name": "Pause",
      "executable": "keyboard:ESC",
      "icon": "\u23F8\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#3b82f6",
      "description": "Microsoft Flight Simulator: Sim",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "ESC",
      "keyboardShortcut": "ESC",
      "position": 15,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    }
  ]
}