{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Destiny 2",
                    "category":  0,
                    "gameTitle":  "Destiny 2",
                    "description":  "Abilities, weapon slots, the Ghost and all four emotes on one deck. Destiny 2 keyboard defaults.",
                    "tags":  "[\"fps\",\"looter-shooter\",\"bungie\",\"co-op\"]",
                    "icon":  "👻",
                    "color":  "#0369a1",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Melee\"},{\"id\":2,\"name\":\"Grenade\"},{\"id\":3,\"name\":\"Super\"},{\"id\":4,\"name\":\"Finisher\"},{\"id\":5,\"name\":\"Jump\"},{\"id\":6,\"name\":\"Reload\"},{\"id\":7,\"name\":\"Kinetic\"},{\"id\":8,\"name\":\"Energy\"},{\"id\":9,\"name\":\"Power\"},{\"id\":10,\"name\":\"Interact\"},{\"id\":11,\"name\":\"Ghost\"},{\"id\":12,\"name\":\"Director\"},{\"id\":13,\"name\":\"Emote 1\"},{\"id\":14,\"name\":\"Emote 2\"},{\"id\":15,\"name\":\"Emote 3\"},{\"id\":16,\"name\":\"Emote 4\"},{\"id\":17,\"name\":\"Sprint\"},{\"id\":18,\"name\":\"Crouch\"}]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Melee",
                     "executable":  "keyboard:C",
                     "icon":  "👊",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Abilities",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "C",
                     "keyboardShortcut":  "C",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Grenade",
                     "executable":  "keyboard:Q",
                     "icon":  "💣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Abilities",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Q",
                     "keyboardShortcut":  "Q",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Super",
                     "executable":  "keyboard:F",
                     "icon":  "🌟",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Abilities",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F",
                     "keyboardShortcut":  "F",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Finisher",
                     "executable":  "keyboard:G",
                     "icon":  "💀",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Abilities",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "G",
                     "keyboardShortcut":  "G",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Jump",
                     "executable":  "keyboard:SPACE",
                     "icon":  "⬆️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Abilities",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SPACE",
                     "keyboardShortcut":  "SPACE",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Reload",
                     "executable":  "keyboard:R",
                     "icon":  "🔁",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Abilities",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "R",
                     "keyboardShortcut":  "R",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Kinetic",
                     "executable":  "keyboard:1",
                     "icon":  "🔫",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1",
                     "keyboardShortcut":  "1",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Energy",
                     "executable":  "keyboard:2",
                     "icon":  "⚡",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2",
                     "keyboardShortcut":  "2",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Power",
                     "executable":  "keyboard:3",
                     "icon":  "🚀",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3",
                     "keyboardShortcut":  "3",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Interact",
                     "executable":  "keyboard:E",
                     "icon":  "🤚",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "E",
                     "keyboardShortcut":  "E",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Ghost",
                     "executable":  "keyboard:TAB",
                     "icon":  "👻",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "TAB",
                     "keyboardShortcut":  "TAB",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Director",
                     "executable":  "keyboard:M",
                     "icon":  "🗺️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "M",
                     "keyboardShortcut":  "M",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Emote 1",
                     "executable":  "keyboard:UP",
                     "icon":  "🕺",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Social",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "UP",
                     "keyboardShortcut":  "UP",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "Emote 2",
                     "executable":  "keyboard:DOWN",
                     "icon":  "💃",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Social",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "DOWN",
                     "keyboardShortcut":  "DOWN",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  15,
                     "name":  "Emote 3",
                     "executable":  "keyboard:LEFT",
                     "icon":  "👋",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Social",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "LEFT",
                     "keyboardShortcut":  "LEFT",
                     "position":  14,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  16,
                     "name":  "Emote 4",
                     "executable":  "keyboard:RIGHT",
                     "icon":  "🙌",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Social",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "RIGHT",
                     "keyboardShortcut":  "RIGHT",
                     "position":  15,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  17,
                     "name":  "Sprint",
                     "executable":  "keyboard:SHIFT",
                     "icon":  "🏃",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Social",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SHIFT",
                     "keyboardShortcut":  "SHIFT",
                     "position":  16,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  18,
                     "name":  "Crouch",
                     "executable":  "keyboard:CTRL",
                     "icon":  "🦆",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0369a1",
                     "description":  "Destiny 2: Social",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL",
                     "keyboardShortcut":  "CTRL",
                     "position":  17,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}