{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Genshin Impact",
                    "category":  0,
                    "gameTitle":  "Genshin Impact",
                    "description":  "Party switching, elemental skill, burst and the menus. Genshin Impact PC defaults.",
                    "tags":  "[\"gacha\",\"open world\",\"action rpg\",\"hoyoverse\"]",
                    "icon":  "⛩️",
                    "color":  "#0d9488",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Character 1\"},{\"id\":2,\"name\":\"Character 2\"},{\"id\":3,\"name\":\"Character 3\"},{\"id\":4,\"name\":\"Character 4\"},null,null,{\"id\":5,\"name\":\"Elemental Skill\"},{\"id\":6,\"name\":\"Elemental Burst\"},{\"id\":7,\"name\":\"Sprint\"},{\"id\":8,\"name\":\"Jump\"},{\"id\":9,\"name\":\"Interact\"},{\"id\":10,\"name\":\"Quick Use\"},{\"id\":11,\"name\":\"Map\"},{\"id\":12,\"name\":\"Inventory\"},{\"id\":13,\"name\":\"Characters\"},{\"id\":14,\"name\":\"Menu\"},null,null]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Character 1",
                     "executable":  "keyboard:1",
                     "icon":  "1️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1",
                     "keyboardShortcut":  "1",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Character 2",
                     "executable":  "keyboard:2",
                     "icon":  "2️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2",
                     "keyboardShortcut":  "2",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Character 3",
                     "executable":  "keyboard:3",
                     "icon":  "3️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3",
                     "keyboardShortcut":  "3",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Character 4",
                     "executable":  "keyboard:4",
                     "icon":  "4️⃣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Party",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4",
                     "keyboardShortcut":  "4",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Elemental Skill",
                     "executable":  "keyboard:E",
                     "icon":  "✨",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "E",
                     "keyboardShortcut":  "E",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Elemental Burst",
                     "executable":  "keyboard:Q",
                     "icon":  "💥",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Q",
                     "keyboardShortcut":  "Q",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Sprint",
                     "executable":  "keyboard:SHIFT",
                     "icon":  "💨",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SHIFT",
                     "keyboardShortcut":  "SHIFT",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Jump",
                     "executable":  "keyboard:SPACE",
                     "icon":  "⬆️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SPACE",
                     "keyboardShortcut":  "SPACE",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Interact",
                     "executable":  "keyboard:F",
                     "icon":  "🤚",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F",
                     "keyboardShortcut":  "F",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Quick Use",
                     "executable":  "keyboard:Z",
                     "icon":  "⚡",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Z",
                     "keyboardShortcut":  "Z",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Map",
                     "executable":  "keyboard:M",
                     "icon":  "🗺️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Menus",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "M",
                     "keyboardShortcut":  "M",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Inventory",
                     "executable":  "keyboard:B",
                     "icon":  "🎒",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Menus",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "B",
                     "keyboardShortcut":  "B",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Characters",
                     "executable":  "keyboard:C",
                     "icon":  "🧍",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Menus",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "C",
                     "keyboardShortcut":  "C",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "Menu",
                     "executable":  "keyboard:ESC",
                     "icon":  "📋",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0d9488",
                     "description":  "Genshin Impact: Menus",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "ESC",
                     "keyboardShortcut":  "ESC",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}