{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Rainbow Six Siege",
                    "category":  0,
                    "gameTitle":  "Tom Clancy\u0027s Rainbow Six Siege",
                    "description":  "Leans, gadgets, drone and camera access, and the comms keys. Siege keyboard defaults.",
                    "tags":  "[\"fps\",\"tactical\",\"competitive\",\"ubisoft\"]",
                    "icon":  "🛡️",
                    "color":  "#1d4ed8",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Lean Left\"},{\"id\":2,\"name\":\"Lean Right\"},{\"id\":3,\"name\":\"Crouch\"},{\"id\":4,\"name\":\"Prone\"},{\"id\":5,\"name\":\"Walk\"},{\"id\":6,\"name\":\"Vault\"},{\"id\":7,\"name\":\"Reload\"},{\"id\":8,\"name\":\"Melee\"},{\"id\":9,\"name\":\"Gadget\"},{\"id\":10,\"name\":\"Reinforce\"},{\"id\":11,\"name\":\"Scan\"},{\"id\":12,\"name\":\"Ping\"},{\"id\":13,\"name\":\"Cameras\"},{\"id\":14,\"name\":\"Drone\"},{\"id\":15,\"name\":\"Scoreboard\"},{\"id\":16,\"name\":\"All Chat\"},{\"id\":17,\"name\":\"Team Chat\"},{\"id\":18,\"name\":\"Mic\"}]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Lean Left",
                     "executable":  "keyboard:Q",
                     "icon":  "◀️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Peek",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Q",
                     "keyboardShortcut":  "Q",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Lean Right",
                     "executable":  "keyboard:E",
                     "icon":  "▶️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Peek",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "E",
                     "keyboardShortcut":  "E",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Crouch",
                     "executable":  "keyboard:C",
                     "icon":  "🦆",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Peek",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "C",
                     "keyboardShortcut":  "C",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Prone",
                     "executable":  "keyboard:CTRL",
                     "icon":  "🛌",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Peek",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL",
                     "keyboardShortcut":  "CTRL",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Walk",
                     "executable":  "keyboard:ALT",
                     "icon":  "👣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Peek",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "ALT",
                     "keyboardShortcut":  "ALT",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Vault",
                     "executable":  "keyboard:SPACE",
                     "icon":  "🤸",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Peek",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SPACE",
                     "keyboardShortcut":  "SPACE",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Reload",
                     "executable":  "keyboard:R",
                     "icon":  "🔁",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Kit",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "R",
                     "keyboardShortcut":  "R",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Melee",
                     "executable":  "keyboard:V",
                     "icon":  "🔪",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Kit",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "V",
                     "keyboardShortcut":  "V",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Gadget",
                     "executable":  "keyboard:G",
                     "icon":  "💣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Kit",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "G",
                     "keyboardShortcut":  "G",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Reinforce",
                     "executable":  "keyboard:F",
                     "icon":  "🧱",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Kit",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F",
                     "keyboardShortcut":  "F",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Scan",
                     "executable":  "keyboard:X",
                     "icon":  "📡",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Kit",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "X",
                     "keyboardShortcut":  "X",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Ping",
                     "executable":  "keyboard:Z",
                     "icon":  "📍",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Kit",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Z",
                     "keyboardShortcut":  "Z",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Cameras",
                     "executable":  "keyboard:5",
                     "icon":  "📹",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "5",
                     "keyboardShortcut":  "5",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "Drone",
                     "executable":  "keyboard:6",
                     "icon":  "🛸",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "6",
                     "keyboardShortcut":  "6",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  15,
                     "name":  "Scoreboard",
                     "executable":  "keyboard:TAB",
                     "icon":  "📊",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "TAB",
                     "keyboardShortcut":  "TAB",
                     "position":  14,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  16,
                     "name":  "All Chat",
                     "executable":  "keyboard:T",
                     "icon":  "💬",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "T",
                     "keyboardShortcut":  "T",
                     "position":  15,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  17,
                     "name":  "Team Chat",
                     "executable":  "keyboard:Y",
                     "icon":  "🗨️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Y",
                     "keyboardShortcut":  "Y",
                     "position":  16,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  18,
                     "name":  "Mic",
                     "executable":  "keyboard:U",
                     "icon":  "🎙️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#1d4ed8",
                     "description":  "Tom Clancy\u0027s Rainbow Six Siege: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "U",
                     "keyboardShortcut":  "U",
                     "position":  17,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}