{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Counter-Strike 2",
                    "category":  0,
                    "gameTitle":  "Counter-Strike 2",
                    "description":  "Buy menu, weapon slots, radio calls and utility bound to one deck. Counter-Strike 2 defaults.",
                    "tags":  "[\"fps\",\"shooter\",\"esports\",\"valve\"]",
                    "icon":  "🔫",
                    "color":  "#f59e0b",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Buy Menu\"},{\"id\":2,\"name\":\"Drop\"},null,null,null,null,{\"id\":3,\"name\":\"Primary\"},{\"id\":4,\"name\":\"Pistol\"},{\"id\":5,\"name\":\"Knife\"},{\"id\":6,\"name\":\"Grenades\"},{\"id\":7,\"name\":\"Bomb\"},{\"id\":8,\"name\":\"Reload\"},{\"id\":9,\"name\":\"Inspect\"},{\"id\":10,\"name\":\"Use\"},null,null,null,null,{\"id\":11,\"name\":\"Radio A\"},{\"id\":12,\"name\":\"Radio B\"},{\"id\":13,\"name\":\"Radio C\"},{\"id\":14,\"name\":\"Team Chat\"},{\"id\":15,\"name\":\"All Chat\"},{\"id\":16,\"name\":\"Voice\"},{\"id\":17,\"name\":\"Walk\"},{\"id\":18,\"name\":\"Crouch\"},{\"id\":19,\"name\":\"Jump\"},null,null,null,{\"id\":20,\"name\":\"Scoreboard\"},{\"id\":21,\"name\":\"Console\"},null,null,null,null]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Buy Menu",
                     "executable":  "keyboard:B",
                     "icon":  "🛒",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Buy",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "B",
                     "keyboardShortcut":  "B",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Drop",
                     "executable":  "keyboard:G",
                     "icon":  "📤",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Buy",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "G",
                     "keyboardShortcut":  "G",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Primary",
                     "executable":  "keyboard:1",
                     "icon":  "🔫",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1",
                     "keyboardShortcut":  "1",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Pistol",
                     "executable":  "keyboard:2",
                     "icon":  "🔪",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2",
                     "keyboardShortcut":  "2",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Knife",
                     "executable":  "keyboard:3",
                     "icon":  "🗡️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3",
                     "keyboardShortcut":  "3",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Grenades",
                     "executable":  "keyboard:4",
                     "icon":  "💣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4",
                     "keyboardShortcut":  "4",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Bomb",
                     "executable":  "keyboard:5",
                     "icon":  "🧨",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "5",
                     "keyboardShortcut":  "5",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Reload",
                     "executable":  "keyboard:R",
                     "icon":  "🔁",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "R",
                     "keyboardShortcut":  "R",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Inspect",
                     "executable":  "keyboard:F",
                     "icon":  "🔍",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F",
                     "keyboardShortcut":  "F",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Use",
                     "executable":  "keyboard:E",
                     "icon":  "🤚",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Weapons",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "E",
                     "keyboardShortcut":  "E",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Radio A",
                     "executable":  "keyboard:Z",
                     "icon":  "📻",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Z",
                     "keyboardShortcut":  "Z",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Radio B",
                     "executable":  "keyboard:X",
                     "icon":  "📻",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "X",
                     "keyboardShortcut":  "X",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Radio C",
                     "executable":  "keyboard:C",
                     "icon":  "📻",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "C",
                     "keyboardShortcut":  "C",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "Team Chat",
                     "executable":  "keyboard:U",
                     "icon":  "💬",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "U",
                     "keyboardShortcut":  "U",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  15,
                     "name":  "All Chat",
                     "executable":  "keyboard:Y",
                     "icon":  "🗨️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Y",
                     "keyboardShortcut":  "Y",
                     "position":  14,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  16,
                     "name":  "Voice",
                     "executable":  "keyboard:K",
                     "icon":  "🎙️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "K",
                     "keyboardShortcut":  "K",
                     "position":  15,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  17,
                     "name":  "Walk",
                     "executable":  "keyboard:SHIFT",
                     "icon":  "🚶",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Movement",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SHIFT",
                     "keyboardShortcut":  "SHIFT",
                     "position":  16,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  18,
                     "name":  "Crouch",
                     "executable":  "keyboard:CTRL",
                     "icon":  "🦆",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Movement",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL",
                     "keyboardShortcut":  "CTRL",
                     "position":  17,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  19,
                     "name":  "Jump",
                     "executable":  "keyboard:SPACE",
                     "icon":  "⬆️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Movement",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SPACE",
                     "keyboardShortcut":  "SPACE",
                     "position":  18,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  20,
                     "name":  "Scoreboard",
                     "executable":  "keyboard:TAB",
                     "icon":  "📊",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Match",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "TAB",
                     "keyboardShortcut":  "TAB",
                     "position":  19,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  21,
                     "name":  "Console",
                     "executable":  "keyboard:BACKTICK",
                     "icon":  "⌨️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#f59e0b",
                     "description":  "Counter-Strike 2: Match",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "BACKTICK",
                     "keyboardShortcut":  "BACKTICK",
                     "position":  20,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}