{
  "formatVersion": "2.1",
  "sanitized": true,
  "exportDate": "2026-07-27T01:19:04.0581498Z",
  "profile": {
    "name": "Palworld Deck",
    "category": 0,
    "gameTitle": "Palworld",
    "description": "Inventory, building, Pal commands and capture bound to one deck. Palworld defaults.",
    "tags": "[\u0022survival\u0022,\u0022crafting\u0022,\u0022coop\u0022]",
    "icon": "\uD83C\uDFA3",
    "color": "#22c55e",
    "backgroundImage": null,
    "executableName": null,
    "isFavorite": false,
    "layoutSettings": "{\u0022gridSize\u0022:6,\u0022appsPerPage\u0022:36,\u0022spacing\u0022:\u0022medium\u0022,\u0022showLabels\u0022:true}",
    "appSettings": "{}"
  },
  "pages": [
    {
      "pageIndex": 0,
      "pageName": "Main",
      "pageData": "[{\u0022id\u0022:188,\u0022name\u0022:\u0022Inventory\u0022},{\u0022id\u0022:189,\u0022name\u0022:\u0022Pal Box\u0022},{\u0022id\u0022:190,\u0022name\u0022:\u0022Map\u0022},{\u0022id\u0022:191,\u0022name\u0022:\u0022Tech Tree\u0022},null,null,{\u0022id\u0022:192,\u0022name\u0022:\u0022Build Menu\u0022},{\u0022id\u0022:193,\u0022name\u0022:\u0022Rotate\u0022},{\u0022id\u0022:194,\u0022name\u0022:\u0022Dismantle\u0022},null,null,null,{\u0022id\u0022:195,\u0022name\u0022:\u0022Throw Pal\u0022},{\u0022id\u0022:196,\u0022name\u0022:\u0022Recall Pal\u0022},{\u0022id\u0022:197,\u0022name\u0022:\u0022Pal Command\u0022},null,null,null,{\u0022id\u0022:198,\u0022name\u0022:\u0022Sprint\u0022},{\u0022id\u0022:199,\u0022name\u0022:\u0022Crouch\u0022},{\u0022id\u0022:200,\u0022name\u0022:\u0022Jump\u0022},{\u0022id\u0022:201,\u0022name\u0022:\u0022Glider\u0022},null,null,{\u0022id\u0022:202,\u0022name\u0022:\u0022Screenshot\u0022},null,null,null,null,null]",
      "layoutConfig": "{}"
    }
  ],
  "apps": [
    {
      "id": 188,
      "name": "Inventory",
      "executable": "keyboard:I",
      "icon": "\uD83C\uDF92",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Menus",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "I",
      "keyboardShortcut": "I",
      "position": 0,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 189,
      "name": "Pal Box",
      "executable": "keyboard:P",
      "icon": "\uD83D\uDCE6",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Menus",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "P",
      "keyboardShortcut": "P",
      "position": 1,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 190,
      "name": "Map",
      "executable": "keyboard:M",
      "icon": "\uD83D\uDDFA\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Menus",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "M",
      "keyboardShortcut": "M",
      "position": 2,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 191,
      "name": "Tech Tree",
      "executable": "keyboard:T",
      "icon": "\uD83D\uDD2C",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Menus",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "T",
      "keyboardShortcut": "T",
      "position": 3,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 192,
      "name": "Build Menu",
      "executable": "keyboard:B",
      "icon": "\uD83D\uDD28",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Building",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "B",
      "keyboardShortcut": "B",
      "position": 4,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 193,
      "name": "Rotate",
      "executable": "keyboard:R",
      "icon": "\uD83D\uDD04",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Building",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "R",
      "keyboardShortcut": "R",
      "position": 5,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 194,
      "name": "Dismantle",
      "executable": "keyboard:X",
      "icon": "\uD83E\uDDE8",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Building",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "X",
      "keyboardShortcut": "X",
      "position": 6,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 195,
      "name": "Throw Pal",
      "executable": "keyboard:E",
      "icon": "\uD83D\uDD34",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Pals",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "E",
      "keyboardShortcut": "E",
      "position": 7,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 196,
      "name": "Recall Pal",
      "executable": "keyboard:F",
      "icon": "\u21A9\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Pals",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "F",
      "keyboardShortcut": "F",
      "position": 8,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 197,
      "name": "Pal Command",
      "executable": "keyboard:C",
      "icon": "\uD83D\uDC3E",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Pals",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "C",
      "keyboardShortcut": "C",
      "position": 9,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 198,
      "name": "Sprint",
      "executable": "keyboard:SHIFT",
      "icon": "\uD83D\uDCA8",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Movement",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "SHIFT",
      "keyboardShortcut": "SHIFT",
      "position": 10,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 199,
      "name": "Crouch",
      "executable": "keyboard:CTRL",
      "icon": "\uD83E\uDD86",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Movement",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "CTRL",
      "keyboardShortcut": "CTRL",
      "position": 11,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 200,
      "name": "Jump",
      "executable": "keyboard:SPACE",
      "icon": "\u2B06\uFE0F",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Movement",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "SPACE",
      "keyboardShortcut": "SPACE",
      "position": 12,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 201,
      "name": "Glider",
      "executable": "keyboard:G",
      "icon": "\uD83E\uDE82",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Movement",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "G",
      "keyboardShortcut": "G",
      "position": 13,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    },
    {
      "id": 202,
      "name": "Screenshot",
      "executable": "keyboard:F12",
      "icon": "\uD83D\uDCF8",
      "iconType": "emoji",
      "iconUrl": null,
      "color": "bg-blue-500",
      "accentColor": "#22c55e",
      "description": "Palworld: Misc",
      "workingDirectory": null,
      "arguments": null,
      "appType": "keyboard",
      "keyCombination": "F12",
      "keyboardShortcut": "F12",
      "position": 14,
      "spanW": 1,
      "spanH": 1,
      "instanceConfig": null,
      "iconSource": null,
      "iconSourcePx": 0,
      "usageCount": 0,
      "lastUsed": null
    }
  ]
}