{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Rocket League",
                    "category":  0,
                    "gameTitle":  "Rocket League",
                    "description":  "Every quick chat as its own button instead of a two-key combo you have to remember mid-air. Rocket League keyboard defaults.",
                    "tags":  "[\"sports\",\"car\",\"esports\",\"psyonix\"]",
                    "icon":  "🚗",
                    "color":  "#0ea5e9",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":4,\"appsPerPage\":16,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"I Got It!\"},{\"id\":2,\"name\":\"Need Boost!\"},{\"id\":3,\"name\":\"Take the Shot!\"},{\"id\":4,\"name\":\"Defending...\"},{\"id\":5,\"name\":\"Nice Shot!\"},{\"id\":6,\"name\":\"Great Pass!\"},{\"id\":7,\"name\":\"Thanks!\"},{\"id\":8,\"name\":\"What a Save!\"},{\"id\":9,\"name\":\"OMG!\"},{\"id\":10,\"name\":\"Noooo!\"},{\"id\":11,\"name\":\"Wow!\"},{\"id\":12,\"name\":\"Close One!\"},{\"id\":13,\"name\":\"$#@%!\"},{\"id\":14,\"name\":\"No Problem\"},{\"id\":15,\"name\":\"Whoops...\"},{\"id\":16,\"name\":\"Sorry!\"},{\"id\":17,\"name\":\"Chat\"},{\"id\":18,\"name\":\"Scoreboard\"},{\"id\":19,\"name\":\"Menu\"},null]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "I Got It!",
                     "executable":  "keyboard:1, 1",
                     "icon":  "🙋",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Information",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1, 1",
                     "keyboardShortcut":  "1, 1",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Need Boost!",
                     "executable":  "keyboard:1, 2",
                     "icon":  "⛽",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Information",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1, 2",
                     "keyboardShortcut":  "1, 2",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Take the Shot!",
                     "executable":  "keyboard:1, 3",
                     "icon":  "🎯",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Information",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1, 3",
                     "keyboardShortcut":  "1, 3",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Defending...",
                     "executable":  "keyboard:1, 4",
                     "icon":  "🛡️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Information",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1, 4",
                     "keyboardShortcut":  "1, 4",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Nice Shot!",
                     "executable":  "keyboard:2, 1",
                     "icon":  "👏",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Compliments",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2, 1",
                     "keyboardShortcut":  "2, 1",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Great Pass!",
                     "executable":  "keyboard:2, 2",
                     "icon":  "🤝",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Compliments",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2, 2",
                     "keyboardShortcut":  "2, 2",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Thanks!",
                     "executable":  "keyboard:2, 3",
                     "icon":  "🙏",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Compliments",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2, 3",
                     "keyboardShortcut":  "2, 3",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "What a Save!",
                     "executable":  "keyboard:2, 4",
                     "icon":  "🧤",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Compliments",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2, 4",
                     "keyboardShortcut":  "2, 4",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "OMG!",
                     "executable":  "keyboard:3, 1",
                     "icon":  "😱",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Reactions",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3, 1",
                     "keyboardShortcut":  "3, 1",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Noooo!",
                     "executable":  "keyboard:3, 2",
                     "icon":  "😭",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Reactions",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3, 2",
                     "keyboardShortcut":  "3, 2",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Wow!",
                     "executable":  "keyboard:3, 3",
                     "icon":  "🤩",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Reactions",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3, 3",
                     "keyboardShortcut":  "3, 3",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Close One!",
                     "executable":  "keyboard:3, 4",
                     "icon":  "😅",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Reactions",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3, 4",
                     "keyboardShortcut":  "3, 4",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "$#@%!",
                     "executable":  "keyboard:4, 1",
                     "icon":  "🤬",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Apologies",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4, 1",
                     "keyboardShortcut":  "4, 1",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "No Problem",
                     "executable":  "keyboard:4, 2",
                     "icon":  "👌",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Apologies",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4, 2",
                     "keyboardShortcut":  "4, 2",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  15,
                     "name":  "Whoops...",
                     "executable":  "keyboard:4, 3",
                     "icon":  "😬",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Apologies",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4, 3",
                     "keyboardShortcut":  "4, 3",
                     "position":  14,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  16,
                     "name":  "Sorry!",
                     "executable":  "keyboard:4, 4",
                     "icon":  "🙇",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Apologies",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4, 4",
                     "keyboardShortcut":  "4, 4",
                     "position":  15,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  17,
                     "name":  "Chat",
                     "executable":  "keyboard:T",
                     "icon":  "💬",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Match",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "T",
                     "keyboardShortcut":  "T",
                     "position":  16,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  18,
                     "name":  "Scoreboard",
                     "executable":  "keyboard:TAB",
                     "icon":  "📊",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Match",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "TAB",
                     "keyboardShortcut":  "TAB",
                     "position":  17,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  19,
                     "name":  "Menu",
                     "executable":  "keyboard:ESC",
                     "icon":  "⏸️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#0ea5e9",
                     "description":  "Rocket League: Match",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "ESC",
                     "keyboardShortcut":  "ESC",
                     "position":  18,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}