{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Deep Rock Galactic",
                    "category":  0,
                    "gameTitle":  "Deep Rock Galactic",
                    "description":  "Weapons, tools, flares and the MULE call on one deck. Rock and Stone.",
                    "tags":  "[\"co-op\",\"fps\",\"mining\",\"dwarves\"]",
                    "icon":  "⛏️",
                    "color":  "#ca8a04",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Primary\"},{\"id\":2,\"name\":\"Secondary\"},{\"id\":3,\"name\":\"Utility Tool\"},{\"id\":4,\"name\":\"Mobility Tool\"},{\"id\":5,\"name\":\"Resupply\"},{\"id\":6,\"name\":\"Reload\"},{\"id\":7,\"name\":\"Flare\"},{\"id\":8,\"name\":\"Grenade\"},{\"id\":9,\"name\":\"Laser Pointer\"},{\"id\":10,\"name\":\"Call M.U.L.E.\"},{\"id\":11,\"name\":\"Terrain Scanner\"},{\"id\":12,\"name\":\"Use\"},{\"id\":13,\"name\":\"Jump\"},{\"id\":14,\"name\":\"Sprint\"},{\"id\":15,\"name\":\"Shout\"},{\"id\":16,\"name\":\"Salute\"},{\"id\":17,\"name\":\"Push to Talk\"},{\"id\":18,\"name\":\"Menu\"}]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Primary",
                     "executable":  "keyboard:1",
                     "icon":  "🔫",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1",
                     "keyboardShortcut":  "1",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Secondary",
                     "executable":  "keyboard:2",
                     "icon":  "🔩",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "2",
                     "keyboardShortcut":  "2",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Utility Tool",
                     "executable":  "keyboard:3",
                     "icon":  "🧰",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "3",
                     "keyboardShortcut":  "3",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Mobility Tool",
                     "executable":  "keyboard:4",
                     "icon":  "🪜",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "4",
                     "keyboardShortcut":  "4",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Resupply",
                     "executable":  "keyboard:5",
                     "icon":  "📦",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "5",
                     "keyboardShortcut":  "5",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Reload",
                     "executable":  "keyboard:R",
                     "icon":  "🔁",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Loadout",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "R",
                     "keyboardShortcut":  "R",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Flare",
                     "executable":  "keyboard:F",
                     "icon":  "🕯️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Gadgets",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F",
                     "keyboardShortcut":  "F",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Grenade",
                     "executable":  "keyboard:G",
                     "icon":  "💣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Gadgets",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "G",
                     "keyboardShortcut":  "G",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Laser Pointer",
                     "executable":  "keyboard:CTRL",
                     "icon":  "🔴",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Gadgets",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL",
                     "keyboardShortcut":  "CTRL",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Call M.U.L.E.",
                     "executable":  "keyboard:C",
                     "icon":  "🤖",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Gadgets",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "C",
                     "keyboardShortcut":  "C",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Terrain Scanner",
                     "executable":  "keyboard:TAB",
                     "icon":  "🗺️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Gadgets",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "TAB",
                     "keyboardShortcut":  "TAB",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Use",
                     "executable":  "keyboard:E",
                     "icon":  "🤚",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Gadgets",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "E",
                     "keyboardShortcut":  "E",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Jump",
                     "executable":  "keyboard:SPACE",
                     "icon":  "⬆️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Crew",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SPACE",
                     "keyboardShortcut":  "SPACE",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  14,
                     "name":  "Sprint",
                     "executable":  "keyboard:SHIFT",
                     "icon":  "🏃",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Crew",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SHIFT",
                     "keyboardShortcut":  "SHIFT",
                     "position":  13,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  15,
                     "name":  "Shout",
                     "executable":  "keyboard:X",
                     "icon":  "📣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Crew",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "X",
                     "keyboardShortcut":  "X",
                     "position":  14,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  16,
                     "name":  "Salute",
                     "executable":  "keyboard:V",
                     "icon":  "🫡",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Crew",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "V",
                     "keyboardShortcut":  "V",
                     "position":  15,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  17,
                     "name":  "Push to Talk",
                     "executable":  "keyboard:Z",
                     "icon":  "🎙️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Crew",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Z",
                     "keyboardShortcut":  "Z",
                     "position":  16,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  18,
                     "name":  "Menu",
                     "executable":  "keyboard:ESC",
                     "icon":  "📋",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#ca8a04",
                     "description":  "Deep Rock Galactic: Crew",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "ESC",
                     "keyboardShortcut":  "ESC",
                     "position":  17,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}