{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "OBS Streaming",
                    "category":  3,
                    "gameTitle":  "OBS Studio",
                    "description":  "Scene switching, mute, replay buffer and marker keys for streaming while you play. Bind these in OBS as global hotkeys.",
                    "tags":  "[\"streaming\",\"obs\",\"capture\"]",
                    "icon":  "🎥",
                    "color":  "#a855f7",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Scene: Game\"},{\"id\":2,\"name\":\"Scene: Cam\"},{\"id\":3,\"name\":\"Scene: BRB\"},{\"id\":4,\"name\":\"Scene: Ending\"},null,null,{\"id\":5,\"name\":\"Mute Mic\"},{\"id\":6,\"name\":\"Mute Desktop\"},null,null,null,null,{\"id\":7,\"name\":\"Start/Stop Stream\"},{\"id\":8,\"name\":\"Start/Stop Record\"},{\"id\":9,\"name\":\"Save Replay\"},{\"id\":10,\"name\":\"Marker\"},null,null]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Scene: Game",
                     "executable":  "keyboard:CTRL+SHIFT+F1",
                     "icon":  "🎮",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Scenes",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+F1",
                     "keyboardShortcut":  "CTRL+SHIFT+F1",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Scene: Cam",
                     "executable":  "keyboard:CTRL+SHIFT+F2",
                     "icon":  "🎥",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Scenes",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+F2",
                     "keyboardShortcut":  "CTRL+SHIFT+F2",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Scene: BRB",
                     "executable":  "keyboard:CTRL+SHIFT+F3",
                     "icon":  "☕",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Scenes",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+F3",
                     "keyboardShortcut":  "CTRL+SHIFT+F3",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Scene: Ending",
                     "executable":  "keyboard:CTRL+SHIFT+F4",
                     "icon":  "👋",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Scenes",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+F4",
                     "keyboardShortcut":  "CTRL+SHIFT+F4",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Mute Mic",
                     "executable":  "keyboard:CTRL+SHIFT+M",
                     "icon":  "🔇",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Audio",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+M",
                     "keyboardShortcut":  "CTRL+SHIFT+M",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Mute Desktop",
                     "executable":  "keyboard:CTRL+SHIFT+D",
                     "icon":  "🔈",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Audio",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+D",
                     "keyboardShortcut":  "CTRL+SHIFT+D",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Start/Stop Stream",
                     "executable":  "keyboard:CTRL+SHIFT+S",
                     "icon":  "🔴",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Broadcast",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+S",
                     "keyboardShortcut":  "CTRL+SHIFT+S",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Start/Stop Record",
                     "executable":  "keyboard:CTRL+SHIFT+R",
                     "icon":  "⏺️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Broadcast",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+R",
                     "keyboardShortcut":  "CTRL+SHIFT+R",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Save Replay",
                     "executable":  "keyboard:CTRL+SHIFT+B",
                     "icon":  "💾",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Broadcast",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+B",
                     "keyboardShortcut":  "CTRL+SHIFT+B",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Marker",
                     "executable":  "keyboard:CTRL+SHIFT+K",
                     "icon":  "🔖",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#a855f7",
                     "description":  "OBS Studio: Broadcast",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL+SHIFT+K",
                     "keyboardShortcut":  "CTRL+SHIFT+K",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}