{
    "formatVersion":  "2.1",
    "sanitized":  true,
    "profile":  {
                    "name":  "Halo Infinite",
                    "category":  0,
                    "gameTitle":  "Halo Infinite",
                    "description":  "Equipment, grenades, weapon swaps and scoreboard for Halo Infinite on keyboard and mouse.",
                    "tags":  "[\"fps\",\"shooter\",\"multiplayer\"]",
                    "icon":  "🪖",
                    "color":  "#16a34a",
                    "backgroundImage":  null,
                    "executableName":  null,
                    "isFavorite":  false,
                    "layoutSettings":  "{\"gridSize\":6,\"appsPerPage\":36,\"spacing\":\"medium\",\"showLabels\":true}",
                    "appSettings":  "{}"
                },
    "pages":  [
                  {
                      "pageIndex":  0,
                      "pageName":  "Main",
                      "pageData":  "[{\"id\":1,\"name\":\"Swap Weapon\"},{\"id\":2,\"name\":\"Melee\"},{\"id\":3,\"name\":\"Frag Grenade\"},{\"id\":4,\"name\":\"Reload\"},null,null,{\"id\":5,\"name\":\"Grapple\"},{\"id\":6,\"name\":\"Drop Wall\"},{\"id\":7,\"name\":\"Threat Sensor\"},null,null,null,{\"id\":8,\"name\":\"Sprint\"},{\"id\":9,\"name\":\"Crouch\"},{\"id\":10,\"name\":\"Jump\"},null,null,null,{\"id\":11,\"name\":\"Scoreboard\"},{\"id\":12,\"name\":\"Mark\"},null,null,null,null,{\"id\":13,\"name\":\"Push to Talk\"},null,null,null,null,null]",
                      "layoutConfig":  "{}"
                  }
              ],
    "apps":  [
                 {
                     "id":  1,
                     "name":  "Swap Weapon",
                     "executable":  "keyboard:1",
                     "icon":  "🔫",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "1",
                     "keyboardShortcut":  "1",
                     "position":  0,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  2,
                     "name":  "Melee",
                     "executable":  "keyboard:V",
                     "icon":  "🤜",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "V",
                     "keyboardShortcut":  "V",
                     "position":  1,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  3,
                     "name":  "Frag Grenade",
                     "executable":  "keyboard:G",
                     "icon":  "💣",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "G",
                     "keyboardShortcut":  "G",
                     "position":  2,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  4,
                     "name":  "Reload",
                     "executable":  "keyboard:R",
                     "icon":  "🔁",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Combat",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "R",
                     "keyboardShortcut":  "R",
                     "position":  3,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  5,
                     "name":  "Grapple",
                     "executable":  "keyboard:Q",
                     "icon":  "🪝",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Equipment",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "Q",
                     "keyboardShortcut":  "Q",
                     "position":  4,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  6,
                     "name":  "Drop Wall",
                     "executable":  "keyboard:F",
                     "icon":  "🧱",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Equipment",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "F",
                     "keyboardShortcut":  "F",
                     "position":  5,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  7,
                     "name":  "Threat Sensor",
                     "executable":  "keyboard:E",
                     "icon":  "📡",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Equipment",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "E",
                     "keyboardShortcut":  "E",
                     "position":  6,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  8,
                     "name":  "Sprint",
                     "executable":  "keyboard:SHIFT",
                     "icon":  "💨",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Movement",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SHIFT",
                     "keyboardShortcut":  "SHIFT",
                     "position":  7,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  9,
                     "name":  "Crouch",
                     "executable":  "keyboard:CTRL",
                     "icon":  "🦆",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Movement",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "CTRL",
                     "keyboardShortcut":  "CTRL",
                     "position":  8,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  10,
                     "name":  "Jump",
                     "executable":  "keyboard:SPACE",
                     "icon":  "⬆️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Movement",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "SPACE",
                     "keyboardShortcut":  "SPACE",
                     "position":  9,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  11,
                     "name":  "Scoreboard",
                     "executable":  "keyboard:TAB",
                     "icon":  "📊",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Match",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "TAB",
                     "keyboardShortcut":  "TAB",
                     "position":  10,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  12,
                     "name":  "Mark",
                     "executable":  "keyboard:T",
                     "icon":  "📍",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Match",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "T",
                     "keyboardShortcut":  "T",
                     "position":  11,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 },
                 {
                     "id":  13,
                     "name":  "Push to Talk",
                     "executable":  "keyboard:B",
                     "icon":  "🎙️",
                     "iconType":  "emoji",
                     "iconUrl":  null,
                     "color":  "bg-blue-500",
                     "accentColor":  "#16a34a",
                     "description":  "Halo Infinite: Comms",
                     "workingDirectory":  null,
                     "arguments":  null,
                     "appType":  "keyboard",
                     "keyCombination":  "B",
                     "keyboardShortcut":  "B",
                     "position":  12,
                     "spanW":  1,
                     "spanH":  1,
                     "instanceConfig":  null,
                     "iconSource":  null,
                     "iconSourcePx":  0,
                     "usageCount":  0,
                     "lastUsed":  null
                 }
             ]
}